cache:
  - c:\cargo\registry
  - c:\cargo\git

init:
  - mkdir c:\cargo
  - mkdir c:\rustup
  - SET PATH=c:\cargo\bin;%PATH%

clone_folder: c:\projects\hpk

environment:
  CARGO_HOME: "c:\\cargo"
  RUSTUP_HOME: "c:\\rustup"
  CARGO_TARGET_DIR: "c:\\projects\\hpk\\target"
  global:
    PROJECT_NAME: "hpk"
  matrix:
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      BITS: 64
      MSYS2: 1
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BITS: 64
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
      BITS: 32
      MSYS2: 1
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
      BITS: 32

matrix:
  fast_finish: true

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --all

before_deploy:
  - cargo build --release
  - mkdir staging
  - copy target\release\hpk.exe staging
  - cd staging
  - 7z a ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip *
  - appveyor PushArtifact ../%PROJECT_NAME%-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.zip

deploy:
  description: "Automatically deployed release"
  artifact: /.*\.zip/
  provider: GitHub
  auth_token:
    secure: Kc6La6kr+yKXcCl5qtpVfP/UCBKhUAF8WGFpkVIz2Oo7/1XeDozDuYQhAI8Wtupa
  on:
    CHANNEL: stable
    appveyor_repo_tag: true

branches:
  only:
    - /v\d+\.\d+\.\d+/
    - master
